// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldEcon.Persistence;

#nullable disable

namespace WorldEcon.Persistence.Migrations
{
    [DbContext(typeof(WorldDbContext))]
    [Migration("20260621061109_InitialGeography")]
    partial class InitialGeography
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("WorldEcon.Domain.Geography.Continent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("continents", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Geography.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContinentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContinentId");

                    b.HasIndex("WorldId");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Geography.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("WorldId");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Geography.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Danger")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Distance")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FromSettlementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Terrain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToSettlementId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromSettlementId");

                    b.HasIndex("ToSettlementId");

                    b.HasIndex("WorldId");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Geography.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Population")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("WorldId");

                    b.ToTable("settlements", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Geography.World", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Calendar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CurrentTick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesetVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Seed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("worlds", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
