// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldEcon.Persistence;

#nullable disable

namespace WorldEcon.Persistence.Migrations
{
    [DbContext(typeof(WorldDbContext))]
    [Migration("20260623001323_AddConsumers")]
    partial class AddConsumers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("WorldEcon.Domain.Economy.Caravan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("ArriveTick")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Delivered")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DepartTick")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GoodId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OriginId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnitCostBasis")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArriveTick");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("WorldId");

                    b.ToTable("caravans", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Economy.Good", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("BaseValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ConsumptionPerCapitaBp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Divisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Need")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ShelfLifeTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("goods", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Economy.ProductionNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Facility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProducerShopId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ThroughputCap")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProducerShopId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("SettlementId");

                    b.HasIndex("WorldId");

                    b.ToTable("production_nodes", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Economy.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Facility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LaborCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lines")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TicksToProduce")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Economy.RepresentativeConsumer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("Budget")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Seat")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Seat");

                    b.HasIndex("WorldId");

                    b.ToTable("consumers", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Economy.RepresentativeMerchant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("Capital")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CargoCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Reach")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Seat")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Seat");

                    b.HasIndex("WorldId");

                    b.ToTable("merchants", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Economy.ResourceEndowment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("Abundance")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GoodId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProducerShopId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProducerShopId");

                    b.HasIndex("SettlementId");

                    b.HasIndex("WorldId");

                    b.ToTable("resource_endowments", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Economy.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MarkupBp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Till")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId");

                    b.HasIndex("WorldId");

                    b.HasIndex("SettlementId", "Kind");

                    b.ToTable("shops", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Economy.Stockpile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CostBasis")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GoodId")
                        .HasColumnType("TEXT");

                    b.Property<long>("MarketPrice")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.HasIndex("OwnerKind", "OwnerId", "GoodId");

                    b.ToTable("stockpiles", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Economy.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CommittedInputCost")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CompleteTick")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductionNodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartTick")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompleteTick");

                    b.HasIndex("ProductionNodeId");

                    b.HasIndex("WorldId");

                    b.ToTable("work_orders", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Geography.Continent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("continents", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Geography.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContinentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContinentId");

                    b.HasIndex("WorldId");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Geography.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("WorldId");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Geography.RegionContainment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChildRegionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentRegionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildRegionId");

                    b.HasIndex("ParentRegionId");

                    b.HasIndex("WorldId");

                    b.ToTable("region_containments", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Geography.RegionContinent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContinentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContinentId");

                    b.HasIndex("RegionId");

                    b.HasIndex("WorldId");

                    b.ToTable("region_continents", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Geography.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Danger")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Distance")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FromSettlementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Terrain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToSettlementId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromSettlementId");

                    b.HasIndex("ToSettlementId");

                    b.HasIndex("WorldId");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Geography.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Population")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("WorldId");

                    b.ToTable("settlements", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Geography.TerritorialClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("WorldId");

                    b.HasIndex("TargetKind", "TargetId");

                    b.ToTable("territorial_claims", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Geography.World", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Calendar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CurrentTick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElasticityExponent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPriceMultBp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinPriceMultBp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesetVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Seed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("worlds", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Logging.LogEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPlayerAction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Magnitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredTick")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OriginId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.HasIndex("WorldId", "Sequence");

                    b.ToTable("log_events", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Logging.LogEventScope", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LogEventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogEventId");

                    b.HasIndex("ScopeKind", "ScopeId", "Sequence");

                    b.ToTable("log_event_scopes", (string)null);
                });

            modelBuilder.Entity("WorldEcon.Domain.Logging.LogEventScope", b =>
                {
                    b.HasOne("WorldEcon.Domain.Logging.LogEvent", null)
                        .WithMany()
                        .HasForeignKey("LogEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
